/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_test */

#ifndef _Included_JNI_test
#define _Included_JNI_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_test
 * Method:    testHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_1test_testHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
